version: 2

project_name: aws-benchmark-collector

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: aws-benchmark-collector
    main: ./cmd
    binary: aws-benchmark-collector
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: scttfrdmn
    name: aws-instance-benchmarks
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"