name: Validate Benchmark Infrastructure

on:
  workflow_dispatch:
  pull_request:
    paths: 
      - '.github/workflows/**'
      - 'pkg/**'
      - 'cmd/**'

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Run tests
      run: |
        go mod tidy
        go test ./... -v
        
    - name: Build CLI tool
      run: |
        go build -o aws-benchmark-collector cmd/main.go
        chmod +x aws-benchmark-collector
        
    - name: Validate CLI help
      run: |
        ./aws-benchmark-collector --help
        ./aws-benchmark-collector run --help
        ./aws-benchmark-collector discover --help